"""add_confidence_material_type_recyclable_to_submissions

Revision ID: 5ea69a82a8df
Revises: a6c524da042f
Create Date: 2026-02-07 07:53:23.028636

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ea69a82a8df'
down_revision: Union[str, Sequence[str], None] = 'a6c524da042f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submissions', sa.Column('confidence', sa.Float(), nullable=True))
    op.add_column('submissions', sa.Column('material_type', sa.String(length=255), nullable=True))
    op.add_column('submissions', sa.Column('recyclable', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('submissions', 'recyclable')
    op.drop_column('submissions', 'material_type')
    op.drop_column('submissions', 'confidence')
    # ### end Alembic commands ###
